- web/app/controllers/DownloadForm.java
fixes #66 
additional manual testing required
> Metadata url hostname

- .gitignore
- build.gradle
- docker-compose.yml
- feedback/src/main/java/nl/idgis/downloadtool/feedback/FeedbackProvider.java
- web/app/DownloadModule.java
- web/app/controllers/ZooKeeper.java
- web/conf/application.conf
> Docker deployment

- Vagrantfile
- docker-compose.yml
- web/app/controllers/DownloadResult.java
- web/app/views/missing.scala.html
- web/conf/application.conf
- web/conf/routes
> Download result

- downloader/src/main/java/nl/idgis/downloadtool/downloader/DownloadProcessor.java
ZIPCACHE_PATH env name corrected and all environment variables are now mandatory.
fixes: #87
> Env vars fix

- downloader/src/main/java/nl/idgis/downloadtool/downloader/DownloadFile.java
- downloader/src/main/java/nl/idgis/downloadtool/downloader/DownloadWfs.java
> check http status code and raise exception when status code != 200

- build.gradle
- docker-compose.yml
- settings.gradle
- web/app/views/layout.scala.html
Version added as:
- ImplementationVersion in manifests
- docker image tag
- text in web frontend
> Version added

- dao/src/main/java/nl/idgis/downloadtool/dao/DownloadDao.java
- db/create_db.sql
Changes to the database schema:
- text -> jsonb
- referential integrity
- unique constraint on logical key
Dao changes:
- various jdbc issues resolved
- query updates required by schema changes
fixes #93
fixes #92
fixes #84
> Database fixes

- .gitignore
- Vagrantfile
- scripts/docker-daemon.sh
- web/app/views/layout.scala.html
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#139
> Whitespace footer text

- docker-compose.yml
- web/app/views/help.scala.html
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#140
connects to IDgis/geoportaal-test#150
connects to IDgis/geoportaal-test#151
> Text fixes

- domain/src/main/java/nl/idgis/downloadtool/domain/AdditionalData.java
- downloader/src/main/java/nl/idgis/downloadtool/downloader/DownloadProcessor.java
- feedback/src/test/java/nl/idgis/downloadtool/test/TestFeedbackProvider.java
- web/app/controllers/DownloadForm.java
- web/app/models/MetadataDocument.java
> Additional data

- build.gradle
- web/app/controllers/DownloadForm.java
connects to IDgis/geoportaal-test#143
connects to IDgis/geoportaal-test#147
> Download files

- web/app/controllers/DownloadResult.java
connects to #104 
connects to IDgis/geoportaal-test#141
> Added content disposition header in response

- web/app/views/form.scala.html
connects to IDgis/geoportaal-test#6
> Added nedstat script

- downloader/src/main/java/nl/idgis/downloadtool/downloader/DownloadFile.java
connects to IDgis/geoportaal-test#179
> Replace spaces in additional data url

- web/app/views/layout.scala.html
- web/public/stylesheets/form-intern.css
connects to IDgis/geoportaal-test#5
> Correct stylesheet form according to header_trusted

- web/app/views/layout.scala.html
- web/conf/application.conf
connects to IDgis/geoportaal-test#5
> Determination of internal on environment variable

- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/DockerRemoteConfig.groovy
- web/app/data/MetadataProvider.java
- web/app/models/MetadataDocument.java
- web/conf/application.conf
Look for a specific useLimitation occurence.
fixes: #122
> Downloadable check

- web/app/views/form.scala.html
fix https://github.com/IDgis/geoportaal-test/issues/153
> In download page SHP radiobutton is selected by default

- docker-compose.yml
fixed https://github.com/IDgis/geoportaal-test/issues/177
> fixed https://github.com/IDgis/geoportaal-test/issues/177

- web/app/views/datasetmissing.scala.html
fixed https://github.com/IDgis/geoportaal-test/issues/184
> 184 dataset not found text

- web/app/views/feedback.scala.html
- web/app/views/form.scala.html
- web/conf/application.conf
connects to IDgis/geoportaal-test#363
> parameterized organisation references for form and feedback

- web/app/controllers/DownloadForm.java
- web/app/views/feedback.scala.html
- web/app/views/form.scala.html
- web/conf/application.conf
connects to IDgis/geoportaal-test#357
> added metadata link reference to form and feedback

- web/app/views/help.scala.html
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#352
> changed help text

- web/app/data/MetadataProvider.java
connects to IDgis/geoportaal-test#465
> don't return 404 for internal deployment even when data is confidential

- web/app/controllers/DownloadRaster.java
connects to IDgis/geopublisher-utrecht#7
> Write raster file in byte array output stream

- build.gradle
- buildSrc/build.gradle
- web/app/views/layout.scala.html
- web/conf/application.conf
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#404
> Css acceptance deployment

- web/app/views/form.scala.html
- web/conf/application.conf
connects to IDgis/geoportaal-test#578
> Add display nedstat configuration and if condition

- web/app/controllers/DownloadForm.java
connects to IDgis/geoportaal-test#473
> Add csv and geojson to outputformats

- web/app/models/DownloadRequest.java
- web/app/views/form.scala.html
connects to IDgis/geoportaal-test#178
> Customize constraints messages for download form

- web/app/views/form.scala.html
- web/conf/application.conf
connects to IDgis/geoportaal-test#598
> Update names for stats analytics, add google analytics

- web/app/views/form.scala.html
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#676
> Add text to form

- web/app/views/form.scala.html
connects to IDgis/geoportaal-test#669
> Remove nedstat and update google analytics

- web/app/controllers/DownloadForm.java
- web/app/models/DownloadInfo.java
- web/app/models/MetadataDocument.java
- web/app/views/form.scala.html
- web/public/stylesheets/form.css
connects to IDgis/geoportaal-test#622
> Add browse graphic url and abstract to form

- web/app/controllers/DownloadForm.java
connects to IDgis/geoportaal-test#673
> Add geopackage

- web/app/views/help.scala.html
connects to IDgis/geoportaal-test#678
> Add geopackage text to help page

- web/app/controllers/DownloadForm.java
- web/app/views/help.scala.html
connects to IDgis/geoportaal-test#673
connects to IDgis/geoportaal-test#678
> Change place of geopackage option in list

- web/app/controllers/DownloadForm.java
connects to IDgis/geoportaal-test#622
> Limit the description to 640 characters

- web/app/views/form.scala.html
connects to IDgis/geoportaal-test#699
> Update google analytics for internal deployment
